OUTPUT_DIR: "checkpoints/sun_16w_2s"
LOG_FILE_NAME: "AttentionNet(vit224,hid:0)_SGD(lr=5e-4)_NCE_Ablation_Global+Attentive+0.01ReMSE(1.0,0.5)_seed=214.log"
MODEL_FILE_NAME: "AttentionNet(vit224,hid:0)_SGD(lr=5e-4)_NCE_Ablation_Global+Attentive+0.01ReMSE(1.0,0.5)_seed=214.pth"
SEED: 214
MODEL:
  META_ARCHITECTURE: "AttentionNet"
  SCALE: 25.0
  HID_DIM: 0
  BACKBONE:
    PRETRAINED: True
    FINETUNE: True
    TYPE: 'vit'
  ATTENTION:
    CHANNEL: 512
    WEIGHT_SHARED: True
    W2V_PATH: "/Datasets/Attribute/w2v"
  LOSS:
    LAMBDA0: 1.0
    LAMBDA1: 0.01
    LAMBDA2: 0.0
    LAMBDA3: 0.0
    REG_NORM: True
    REG_TYPE: "MSE"
  REZSL:
    USE: True
    P: 1.0
    P2: 0.5
    WEIGHT_TYPE: "cross_batch"

DATASETS:
  NAME: "SUN"
  IMAGE_SIZE: 224
  WAYS: 16
  SHOTS: 2
  SEMANTIC: 'original'

DATALOADER:
  MODE: 'episode'
  N_BATCH: 300

SOLVER:
  MAX_EPOCH: 30
  BASE_LR: 5e-4
  WEIGHT_DECAY: 1e-5
  MOMENTUM: 0.9
  GAMMA: 0.5
  STEPS: 10
  DATA_AUG: "resize_random_crop"

TEST:
  IMS_PER_BATCH: 32
  DATA_AUG: "resize_crop"
  GAMMA: 0.7
